language: python
dist: focal

python: 
 - "3.8"
 - "3.9"
 - "3.10"

install:
  - pip install pip --upgrade
  - pip install poetry setuptools==50.3.2
  - poetry install

script:
    make lint && make test

branches:
  - master
  - develop
