language: python
dist: focal

python: 
 - "3.8"
 - "3.9"
 - "3.10"
 - "3.11-dev"

install:
  - pip install pip --upgrade
  - pip install poetry==1.1.15 setuptools==50.3.2
  - poetry install

script:
    make lint && make test

branches:
  - master
  - develop
