language: python
dist: jammy

python: 
 - "3.9"
 - "3.10"
 - "3.11"
 - "3.12"
 - "3.13"
install:
  - pip install pip --upgrade
  - pip install "poetry<2.2"
  - poetry install

script:
    make lint && make test

branches:
  only:
    - master
    - develop
