target-version = "py39"
line-length = 120

[lint]
select = [
    "E", # Error
    "F", # Pyflakes
    "W", # Warning
    "I", # isort
    "B",  # flake8-bugbear
    "NPY", # NumPy-specific rules
    "RUF", # Ruff-specific rules
    "FURB" # refurb
]

ignore = [
    "RUF001", # 全角記号など`ambiguous unicode character`も使いたいため
    "RUF002",# 全角記号など`ambiguous unicode character`も使いたいため
    "RUF003",# 全角記号など`ambiguous unicode character`も使いたいため
]
